const Action = {
	ADD_TASK: 'ADD_TASK',
	DELETE_TASK: 'DELETE_TASK',
	EDIT_TASK: 'EDIT_TASK',
	SET_CHECK: 'SET_CHECK',
	SET_CHECK_ALL: 'SET_CHECK_ALL',
	REMOVE_TASK: 'REMOVE_TASK',
	CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}

export default Action;